name: gerencie-service

volumes:
  gerencie_db_data: {}

services:
  api:
    image: pedidos-service
    environment:
      GERENCIE_PROFILE: dev
      GERENCIE_DB_USER: postgres
      GERENCIE_DB_PASSWORD: postgres
      GERENCIE_DB_HOST: postgresql://db
      GERENCIE_DB_PORT: 5432
      PORT: 8080
    networks:
      - gerencie-net
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - gerencie_db_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gerenciedb_dev
    networks:
      - gerencie-net
    expose:
      - 5432

networks:
  gerencie-net:
    driver: bridge